### ISSUE TITLE
Use HPKP

### ISSUE THREAD

**Issue by dannycoates** [mozilla/something-awesome#109]
https://wiki.mozilla.org/Security/Guidelines/Web_Security#HTTP_Public_Key_Pinning

@relud are we planning on running this behind nginx in prod? We'd use a similar solution to screenshots then yeah? https://github.com/mozilla-services/cloudops-deployment/pull/742

**Comment by relud** [comment]
yes, and we can do that.

**Comment by relud** [comment]
this is resolved
