### ISSUE TITLE
Add dockerflow endpoints

### ISSUE THREAD

**Issue by relud** [mozilla/something-awesome#117]
- [ ] We should add a `/__heartbeat__` endpoint that touches s3 and redis, and returns 500 if unreachable, and emits a statsd metric like `heartbeat.pass` and `heartbeat.fail` for monitoring
- [x] We should add a `/__lbheartbeat__` that just returns 200
- [ ] We should add a `/__version__` endpoint that responds with a json object that has the fields `commit`, `source`, and `version`

**Comment by relud** [comment]
this is a duplicate

**Comment by pdehaan** [comment]
Ref: _"Add /\_\_heartbeat\_\_ route (#34)"_, and _"Add /\_\_version\_\_ route? (#33)"_.
