### ISSUE TITLE
[Stage] The generated links are already expired, even if were never used 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/something-awesome#129]
[Notes]:
- I am not sure if this happens because the stage page is not up to date or there really is an actual issue.

[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://fileshare.stage.mozaws.net" page.
2. Upload a file and copy the generated link.
3. Open a new tab and navigate to the generated link.
4. Observe the page.

[Expected result]:
- The link is not expired and you can download the file.

[Actual results]:
- "The link has expired or never existed in the first place" message is displayed.

[Additional Notes]:
- This issue is not reproducible on dev page ("https://fileshare.dev.mozaws.net").
- Here is a screen recording with the issue:
![shared links are expired](https://user-images.githubusercontent.com/19226534/27486259-b2dc769e-5838-11e7-91ba-f7b58feba162.gif)

**Comment by dannycoates** [comment]
fixed on stage in v0.1.2 http://fileshare.stage.mozaws.net/__version__
