### ISSUE TITLE
Homepage shows table headings before files have been uploaded

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#140]
Found in https://fileshare.stage.mozaws.net/__version__ (a7fcb1a):

```json
{
  "commit": "a7fcb1a",
  "source": "https://github.com/mozilla/something-awesome/",
  "version": "0.1.2"
}
```

---

Before you upload a single file, you still see the `<table>` headers for _"File"_, _"Copy URL"_, _"Expires in"_, and _"Delete"_:

<img width="654" alt="firefox_fileshare" src="https://user-images.githubusercontent.com/557895/27506254-c03e4fa2-5869-11e7-8f27-87cfecca68af.png">

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page (https://fileshare.dev.mozaws.net/).
