### ISSUE TITLE
Download links do not expire after the timer runs out

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/something-awesome#156]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://fileshare.dev.mozaws.net/" page.
2. Upload a file and copy the link.
3. Wait for the timer to run out and paste the link in the URL bar.
4. Press enter and observe the behavior.

[Expected result]:
- The "Link expired" page is displayed.

[Actual results]:
- The page is loaded and the file can be downloaded.

[Notes]:
- On https://fileshare.stage.mozaws.net/ the timer is not displayed, so the link never expires.
- Here is a screen recording with the issue:
![file not expired after timer runs out](https://user-images.githubusercontent.com/18304511/27832481-85cd07b6-60d7-11e7-9e76-b01c192a32c2.gif)

**Comment by wresuolc** [comment]
This was a dev issue.  Files are still deleted after 24hr
