### ISSUE TITLE
Rename stage/dev servers to "send.stage.mozaws.net"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#166]
Per https://github.com/mozilla/something-awesome/issues/7#issuecomment-313438598:

> @pdehaan says: "Does this mean we want to rename the stage/dev servers from something like https://fileshare.stage.mozaws.net/ to https://send.stage.mozaws.net/?"
>
> @clouserw says: "urgh. Sorry @relud -- how hard is it to change these now? If it's difficult or bad timing it doesn't need to happen right away."

**Comment by pdehaan** [comment]
Once this is done, we'll need to update (at least) the README.md file and public/contribute.json file (after/if #148 lands).

**Comment by pdehaan** [comment]
Me thinks this is done. Closing.

**Comment by relud** [comment]
this is still blocked on #167 before it's fully done
