### ISSUE TITLE
Hosted app still mentions localhost server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#31]
Per: _Host something on AWS #2_, we now have a https://p2p.dev.lcip.org/ dev server. But when I try uploading/downloading files, I still see some references to "localhost".

We'll need to try determining the environment at runtime to distinguish between local and dev server stuffs.

---

Other than that, everything worked and looked great! Awesome work, @abhinadduri!

**Comment by dannycoates** [comment]
this is fixed now
