### ISSUE TITLE
Add /__version__ route?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#33]
Re: https://p2p.dev.lcip.org

Speaking of interesting challenges, creating a `/__version__` route which lets us (friendly neighborhood QA) know exactly what code (Git SHA) is deployed on the dev/stage/prod server and would be pretty useful [eventually].

Currently https://p2p.dev.lcip.org/__version__ returns a 404 (as expected).

Here's a sample of what we get back from something like TestPilot prod server (https://testpilot.firefox.com/__version__):

```json
{
  "commit": "c4639a25b938bd4717aadc3ead840e80f0a0f059",
  "version": "2017-05-04",
  "source": "https://github.com/mozilla/testpilot"
}
```

**Comment by wresuolc** [comment]
The response should have the header Content-Type: application/json.

The response should contain source, version, and commit as top level fields.

Example:
{
    "source": "https://github.com/mozilla/onyx",
    "version": "1.4.16",
    "commit": "c39d721edd431a6264da684a5e48a403ad07e221"
}
