### ISSUE TITLE
Host our own version of jQuery and other vendored code

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#48]
Currently we're hot linking to a hosted version of [**jquery@3.2.1** on ajax.googleapis.com](https://github.com/mozilla/something-awesome/search?utf8=%E2%9C%93&q=jquery&type=):

```html
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
```

We should host jQuery locally so we aren't using third party servers. Not sure if we want to grab it via npm and bundle it w/ Webpack or Rollup or whatever.

**Comment by abhinadduri** [comment]
Grabbed a local version of jquery.min.js

**Comment by abhinadduri** [comment]
Update: changed to using the npm version
