### ISSUE TITLE
Check previous uploads

### ISSUE THREAD

**Issue by dannycoates** [mozilla/something-awesome#59]
We should check the previous uploads list against the server to see if they're still available. This should have it's own server endpoint that the frontend can use.

**Comment by abhinadduri** [comment]
I've added a route "/exists/:id" that sends a 200 if the link still exists and a 404 if it's been deleted. Is this enough for this issue? The front end can poll on an interval and act accordingly

**Comment by dnarcese** [comment]
Fixed in #154
