### ISSUE TITLE
Download URLs don't wrap in Google Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#73]
Running the [**ui** (drag & drop)](https://github.com/mozilla/something-awesome/pull/71) branch locally and noticed that the **Copy URL** doesn't word wrap in Google Chrome.

Not sure if we want to try force-wrapping the URL versus single-line w/ truncation.

<img width="719" alt="firefox_fileshare" src="https://user-images.githubusercontent.com/557895/26954538-615eeba0-4c65-11e7-9a2c-6f2ee1dda7f0.png">
**Figure 1:** Firefox Nightly.

---

<img width="719" alt="firefox_fileshare" src="https://user-images.githubusercontent.com/557895/26954581-968b2dde-4c65-11e7-9e81-d2f81fa70fb5.png">
**Figure 2:** Chome Release channel.

**Comment by dannycoates** [comment]
UI is changing
