### ISSUE TITLE
Duplicate `upload-img` id in views/index.handlebars

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#82]
Ref: [/views/index.handlebars:18](https://github.com/mozilla/something-awesome/blob/8baa6d096461670fc395e5c68f02c413e273dacb/views/index.handlebars#L18) and [/views/index.handlebars:54](https://github.com/mozilla/something-awesome/blob/8baa6d096461670fc395e5c68f02c413e273dacb/views/index.handlebars#L54):

```html
<div id="upload-img"><img src="/resources/upload.svg" alt="Upload" /></div>
```

---

You can see this in person by running `npm run lint:html` from the CLI.

### Output:

```sh
...
> portal-alpha@1.0.0 lint:html /Users/pdehaan/dev/github/mozilla/something-awesome
> htmllint 'views/*.handlebars'

views/index.handlebars: line 54, col 13, the id "upload-img" is already in use

[htmllint] found 1 errors out of 2 files
```

**Comment by abhinadduri** [comment]
Only one of those is actually rendered, based on the data passed into the view. The reason it's this way is to populate the file name and size before sending the html back to the client
