### ISSUE TITLE
Audit server's sync methods

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#83]
I noticed we have a few `*Sync` methods in the code. Not sure how performant those will be if we get oodles of 2GB files being stored to disk.

Ref: [**eslint**'s `no-sync` rule](http://eslint.org/docs/rules/no-sync)

```sh
$ npm run lint:js

/Users/pdehaan/dev/github/mozilla/something-awesome/server/storage.js
   70:15  warning  Unexpected sync method: 'statSync'    no-sync
  108:17  warning  Unexpected sync method: 'unlinkSync'  no-sync
  117:13  warning  Unexpected sync method: 'unlinkSync'  no-sync
```

Not sure if we should try converting those sync functions to promises or something less blocking.

**Comment by dannycoates** [comment]
disk is for local dev only. NBD
