### ISSUE TITLE
[Enhancement] After the "Copy" button is clicked and a few seconds past, the button should be changed back in the "Copy" state

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/something-awesome#84]
[Notes]:
- If the button remains in the "Copied" state, the user don't have the possibility any more to use the "Copy" button again. 
- A similar functionality is implemented in the Screenshots "Share" panel.

[Affected versions]:
- Firefox 53.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://p2p.dev.lcip.org/" page.
2. Upload a file and click the "Copy" button.
3. Observe the "Copy" button.

[Expected result]:
- The "Copy" button is changed into a green "Copied" button and after a few seconds the button is changed back in the "Copy" button.

[Actual results]:
- The "Copy" button is changed into a green "Copied" button and if it's click again nothing happens.

**Comment by dannycoates** [comment]
fixed in #105
