### ISSUE TITLE
After resizing the browser, the background image no longer feels the resized area

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/something-awesome#85]
[Affected versions]:
- Firefox 53.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://p2p.dev.lcip.org/" page.
2. Maximize the browser.
3. Restore the browser.
4. Observe the background image.

[Expected result]:
- The background image is responsive and it's correctly displayed when resizing the browser.

[Actual results]:
- The background image is not correctly displayed ant two two images can be observed.

[Notes]:
- Here is a screen shot with the issue: https://goo.gl/Ol7uja

**Comment by sevaan** [comment]
I believe this is a Wontfix for this design as all the visuals including the background are temporary right now.

We should make sure this is taken into consideration for the new visuals though if necessary.

**Comment by sevaan** [comment]
I just looked at some drafts of the new visuals and it looks like we will need that responsive background.

**Comment by dannycoates** [comment]
The UI is changing soon
